#
# Module manifest for module 'GOAL.BMC.AO.Interop'
#
# Generated by: ZKR00RU
#
# Generated on: 28/07/2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'GOAL.BMC.AO.Interop'

# Version number of this module.
ModuleVersion = '1.0.0.100'

# ID used to uniquely identify this module
GUID = '7b12130a-2b08-454b-8e16-bc05c6077f64'

# Author of this module
Author = 'Global Operations Analytics'

# Company or vendor of this module
CompanyName = 'Bank of America'

# Copyright statement for this module
Copyright = '(c) 2017 Bank of America. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Powershell Module Wrapper for BMC Atrium Orchestrator REST API operations.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
#ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module. N.B. Marking as Verb-Noun being public functions.
FunctionsToExport = '*-*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
